version: '3.7'
services:
    db:
        image: 'arm32v7/postgres:13.1'
        container_name: sabonah.db
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=sabonah_postgres
            - POSTGRES_PASSWORD=click123
            - POSTGRES_DB=sabonah_db
        volumes:
            - 'sabonah_postgres_data:/var/lib/postgresql'

    redis:
        container_name: sabonah.redis
        image: 'arm32v7/redis:6.0.9'
        ports:
            - 6379:6379
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - 'sabonah_redis_data:/bitnami'

volumes:
    sabonah_postgres_data:
        external: true
    sabonah_redis_data:
        external: true
